In [1]:
import numpy as np

# **** on the x-axis: apples, beef, eggs and potatoes
#      on the y-axis: Carbs, Protein and Fat ****
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print("A: " + str(A))
print("A.shape: " + str(A.shape))

A: [[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
A.shape: (3, 4)


In [2]:
# **** sums all values in A ****
cal = A.sum()
print("cal: " + str(cal))
print("cal.shape: " + str(cal.shape))

cal: 530.3000000000001
cal.shape: ()


In [3]:
# **** sum all colums in A ****
cal = A.sum(axis=0)
print("cal: " + str(cal))
print("cal.shape: " + str(cal.shape))

cal: [ 59.  239.  155.4  76.9]
cal.shape: (4,)


In [4]:
# **** compute percentages (every column in A was divided by every column in cal) ****
percentage = (A / cal) * 100.0
print("percentage:\n" + str(percentage))
print("percentage.shape: " + str(percentage.shape))

percentage:
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
percentage.shape: (3, 4)


In [5]:
# **** each column in A was divided by the corresponding column in cal ****
percentage = (A / cal.reshape(1, 4)) * 100.0
print("percentage:\n" + str(percentage))
print("percentage.shape: " + str(percentage.shape))

percentage:
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
percentage.shape: (3, 4)


In [6]:
# **** a different example ****
B = np.array([1, 2, 3, 4])
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))
print()

B += 100
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))

B:
[1 2 3 4]
B.shape: (4,)

B:
[101 102 103 104]
B.shape: (4,)


In [7]:
# ***** ****
B = np.array([[1 ,2, 3, 4]])
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))

B += 100
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))

B:
[[1 2 3 4]]
B.shape: (1, 4)
B:
[[101 102 103 104]]
B.shape: (1, 4)


In [8]:
# **** ****
B = np.array([[1], [2], [3], [4]])
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))
print()

B += 100
print("B:\n" + str(B))
print("B.shape: " + str(B.shape))

B:
[[1]
 [2]
 [3]
 [4]]
B.shape: (4, 1)

B:
[[101]
 [102]
 [103]
 [104]]
B.shape: (4, 1)


In [9]:
# **** yet one more example ****
C = np.array([[1, 2, 3],
              [4, 5, 6]])
print("C:\n" + str(C))
print("C.shape: " + str(C.shape))
print()

D = np.array([[100, 200, 300]])
print("D:\n" + str(D))
print("D.shape: " + str(D.shape))

C:
[[1 2 3]
 [4 5 6]]
C.shape: (2, 3)

D:
[[100 200 300]]
D.shape: (1, 3)


In [10]:
# **** C[2,3] + D[1,3] broadcasted to: C[2,3] + D[2,3] = E[2,3]
E = C + D
print("E:\n" + str(E))
print("E.shape: " + str(E.shape))

E:
[[101 202 303]
 [104 205 306]]
E.shape: (2, 3)


In [11]:
# **** one last example ****
F = np.array([[1, 2, 3],
              [4, 5, 6]])
print("F:\n" + str(F))
print("F.shape: " + str(F.shape))

F:
[[1 2 3]
 [4 5 6]]
F.shape: (2, 3)


In [12]:
G = np.array([[100],
              [200]])
print("G:\n" + str(G))
print("G.shape" + str(G.shape))

G:
[[100]
 [200]]
G.shape(2, 1)


In [13]:
# **** F[2,3] + G[2,1] broadcasted to: F[2,3] + G[2,3] = H[2,3]****
H = F + G
print("H:\n" + str(H))
print("H.shape: " + str(H.shape))

H:
[[101 102 103]
 [204 205 206]]
H.shape: (2, 3)
